# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
   - linux
   - osx

before_install:
   - if [ "$TRAVIS_OS_NAME" = "linux"]; then sudo add-apt-repository -y ppa:cran/imagemagick; fi
   - if [ "$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get update; fi
   - if [ "$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get install -y libmagick++-dev; fi

after_success:
  - Rscript -e 'covr::codecov()'
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
